apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: xai
  name: xai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xai
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xai
    spec:
      containers:
      - image: gcr.io/hclsw-gcp-xai/jenkins/xaidockerimg:latest
        name: xai
        resources: {}
status: {}

