apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: xai-keyword-extraction-c6-7
spec:
  predictor:
    minReplicas: 0
    containers:
      - image: gcr.io/hclsw-gcp-xai/kwe-custom-predictor-xai:v5
        name: kserve-container	
        resources:	
          limits:	
            cpu: '1'	
            memory: 2Gi	
          requests:	
            cpu: '1'	
            memory: 2Gi
